<?php
$jobs = [
    0  => ['full_name' => 'None', 'abbreviation' => 'NONE'],
    1  => ['full_name' => 'Warrior', 'abbreviation' => 'WAR'],
    2  => ['full_name' => 'Monk', 'abbreviation' => 'MNK'],
    3  => ['full_name' => 'White Mage', 'abbreviation' => 'WHM'],
    4  => ['full_name' => 'Black Mage', 'abbreviation' => 'BLM'],
    5  => ['full_name' => 'Red Mage', 'abbreviation' => 'RDM'],
    6  => ['full_name' => 'Thief', 'abbreviation' => 'THF'],
    7  => ['full_name' => 'Paladin', 'abbreviation' => 'PLD'],
    8  => ['full_name' => 'Dark Knight', 'abbreviation' => 'DRK'],
    9  => ['full_name' => 'Beastmaster', 'abbreviation' => 'BST'],
    10 => ['full_name' => 'Bard', 'abbreviation' => 'BRD'],
    11 => ['full_name' => 'Ranger', 'abbreviation' => 'RNG'],
    12 => ['full_name' => 'Samurai', 'abbreviation' => 'SAM'],
    13 => ['full_name' => 'Ninja', 'abbreviation' => 'NIN'],
    14 => ['full_name' => 'Dragoon', 'abbreviation' => 'DRG'],
    15 => ['full_name' => 'Summoner', 'abbreviation' => 'SMN'],
    16 => ['full_name' => 'Blue Mage', 'abbreviation' => 'BLU'],
    17 => ['full_name' => 'Corsair', 'abbreviation' => 'COR'],
    18 => ['full_name' => 'Puppetmaster', 'abbreviation' => 'PUP'],
    19 => ['full_name' => 'Dancer', 'abbreviation' => 'DNC'],
    20 => ['full_name' => 'Scholar', 'abbreviation' => 'SCH'],
    21 => ['full_name' => 'Geomancer', 'abbreviation' => 'GEO'],
    22 => ['full_name' => 'Rune Fencer', 'abbreviation' => 'RUN'],
    23 => ['full_name' => 'Monster', 'abbreviation' => 'MON'],
];